
services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - my-networks
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow
    env_file:
      - .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: >
      bash -c "
        airflow db init &&
        airflow db migrate &&
        airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com &&
        airflow scheduler & airflow webserver
      "
    networks:
      - my-networks

networks:
  my-networks:
    driver: bridge

volumes:
  postgres_data:
